const express=require("express"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),multer=require("multer"),{Pool}=require("pg"),path=require("path");
const app=express(),PORT=process.env.PORT||10000,SECRET=process.env.JWT_SECRET||"dev-secret-change-me";
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false}):null;
app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public")));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
async function q(sql,p=[]){if(!pool)throw Error("DATABASE_URL is missing. Connect a Render PostgreSQL database.");return pool.query(sql,p)}
async function init(){await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL)`);
await q(`CREATE TABLE IF NOT EXISTS profiles(user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,experience TEXT DEFAULT 'Fresher',role TEXT DEFAULT '',location TEXT DEFAULT '',skills TEXT DEFAULT '')`);
await q(`CREATE TABLE IF NOT EXISTS saved(user_id INT REFERENCES users(id) ON DELETE CASCADE,job_id INT,PRIMARY KEY(user_id,job_id))`);
await q(`CREATE TABLE IF NOT EXISTS applications(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,job_id INT,status TEXT DEFAULT 'Applied',created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(user_id,job_id))`);
await q(`CREATE TABLE IF NOT EXISTS resumes(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,filename TEXT,analysis JSONB,created_at TIMESTAMPTZ DEFAULT NOW())`);
await q(`CREATE TABLE IF NOT EXISTS interviews(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,role TEXT,score INT,answers JSONB,created_at TIMESTAMPTZ DEFAULT NOW())`)}
const jobs=[
{id:1,title:"Frontend Developer Intern",company:"PixelSpring",location:"Hyderabad / Remote",level:"Fresher",type:"Internship",salary:"₹15k–₹25k/month",skills:["HTML","CSS","JavaScript","React"],description:"Entry-level frontend role with mentorship."},
{id:2,title:"Graduate Software Engineer",company:"Northstar Labs",location:"Bengaluru",level:"Fresher",type:"Full-time",salary:"₹4–7 LPA",skills:["Java","SQL","Git"],description:"Graduate engineering role with training."},
{id:3,title:"Junior React Developer",company:"CloudMint",location:"Remote",level:"0–1 years",type:"Full-time",salary:"₹5–8 LPA",skills:["React","JavaScript","TypeScript"],description:"Build modern frontend experiences."},
{id:4,title:"Data Analyst Trainee",company:"MetricLeaf",location:"Chennai",level:"Fresher",type:"Trainee",salary:"₹3–5 LPA",skills:["SQL","Excel","Python"],description:"Reporting and data quality projects."},
{id:5,title:"Backend Developer",company:"StackHarbor",location:"Pune",level:"2+ years",type:"Full-time",salary:"₹10–16 LPA",skills:["Node.js","PostgreSQL","APIs"],description:"Backend services role requiring experience."},
{id:6,title:"QA Engineer Intern",company:"BrightTest",location:"Remote",level:"Fresher",type:"Internship",salary:"₹12k–₹20k/month",skills:["Testing","SQL","JavaScript"],description:"Learn testing, bug reporting, and automation."}];
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer /,""),SECRET);next()}catch{return res.status(401).json({error:"Please log in again."})}}
app.get("/api/health",(req,res)=>res.json({ok:true,database:!!pool}));
app.post("/api/register",async(req,res)=>{try{let{name,email,password}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:"Name, email and password (8+ characters) are required."});let hash=await bcrypt.hash(password,12),r=await q("INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email",[name,email.toLowerCase(),hash]),u=r.rows[0];await q("INSERT INTO profiles(user_id) VALUES($1)",[u.id]);res.json({token:jwt.sign({id:u.id},SECRET,{expiresIn:"7d"}),user:u})}catch(e){res.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"Email already registered.":"Registration failed. Check database."})}});
app.post("/api/login",async(req,res)=>{try{let r=await q("SELECT * FROM users WHERE email=$1",[(req.body.email||"").toLowerCase()]),u=r.rows[0];if(!u||!await bcrypt.compare(req.body.password||"",u.password_hash))return res.status(401).json({error:"Email or password is incorrect."});res.json({token:jwt.sign({id:u.id},SECRET,{expiresIn:"7d"}),user:{id:u.id,name:u.name,email:u.email}})}catch(e){res.status(500).json({error:"Login failed. Check database."})}});
app.get("/api/me",auth,async(req,res)=>{let r=await q("SELECT u.id,u.name,u.email,p.experience,p.role,p.location,p.skills FROM users u JOIN profiles p ON p.user_id=u.id WHERE u.id=$1",[req.user.id]);res.json(r.rows[0]||{})});
app.put("/api/profile",auth,async(req,res)=>{let b=req.body;await q("UPDATE users SET name=$1 WHERE id=$2",[b.name,req.user.id]);let r=await q("UPDATE profiles SET experience=$1,role=$2,location=$3,skills=$4 WHERE user_id=$5 RETURNING *",[b.experience,b.role,b.location,b.skills,req.user.id]);res.json(r.rows[0])});
app.get("/api/jobs",(req,res)=>{let{q="",level="",location="",type=""}=req.query;res.json(jobs.filter(j=>(!q||JSON.stringify(j).toLowerCase().includes(q.toLowerCase()))&&(!level||j.level===level)&&(!location||j.location.toLowerCase().includes(location.toLowerCase()))&&(!type||j.type===type)))});
app.get("/api/saved",auth,async(req,res)=>{let r=await q("SELECT job_id FROM saved WHERE user_id=$1",[req.user.id]);res.json(r.rows.map(x=>x.job_id))});
app.post("/api/saved/:id",auth,async(req,res)=>{let id=+req.params.id,r=await q("SELECT 1 FROM saved WHERE user_id=$1 AND job_id=$2",[req.user.id,id]);if(r.rowCount)await q("DELETE FROM saved WHERE user_id=$1 AND job_id=$2",[req.user.id,id]);else await q("INSERT INTO saved(user_id,job_id) VALUES($1,$2)",[req.user.id,id]);res.json({saved:!r.rowCount})});
app.get("/api/applications",auth,async(req,res)=>{let r=await q("SELECT * FROM applications WHERE user_id=$1 ORDER BY created_at DESC",[req.user.id]);res.json(r.rows.map(a=>({...a,job:jobs.find(j=>j.id===a.job_id)})))});
app.post("/api/applications/:id",auth,async(req,res)=>{let r=await q("INSERT INTO applications(user_id,job_id,status) VALUES($1,$2,'Applied') ON CONFLICT(user_id,job_id) DO UPDATE SET status='Applied' RETURNING *",[req.user.id,+req.params.id]);res.json(r.rows[0])});
app.patch("/api/applications/:id",auth,async(req,res)=>{let allowed=["Applied","Assessment","Interview","Offer","Rejected","Withdrawn"];if(!allowed.includes(req.body.status))return res.status(400).json({error:"Invalid status"});let r=await q("UPDATE applications SET status=$1 WHERE id=$2 AND user_id=$3 RETURNING *",[req.body.status,+req.params.id,req.user.id]);res.json(r.rows[0])});
app.delete("/api/applications/:id",auth,async(req,res)=>{await q("DELETE FROM applications WHERE id=$1 AND user_id=$2",[+req.params.id,req.user.id]);res.json({ok:true})});
app.post("/api/resume",auth,upload.single("resume"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"Choose a file first"});let text=[".txt",".md"].includes(path.extname(req.file.originalname).toLowerCase())?req.file.buffer.toString():"";let checks=[["Contact details",/email|@|phone/i.test(text)],["Skills",/skills/i.test(text)],["Education",/education|degree|college|university/i.test(text)],["Projects/experience",/project|experience|internship/i.test(text)],["Action verbs",/built|created|developed|implemented/i.test(text)]],analysis={score:40+checks.filter(x=>x[1]).length*12,checks,suggestions:checks.filter(x=>!x[1]).map(x=>"Review "+x[0])};await q("INSERT INTO resumes(user_id,filename,analysis) VALUES($1,$2,$3)",[req.user.id,req.file.originalname,JSON.stringify(analysis)]);res.json({analysis,note:text?"Basic text checks completed.":"File received; PDF/DOCX text extraction needs a parser."})});
app.post("/api/interview",auth,async(req,res)=>{let answers=(req.body.answers||[]).filter(x=>String(x).trim()),score=Math.min(100,Math.round(answers.length/5*55+Math.min(answers.join(" ").split(/\\s+/).length,200)/200*45));await q("INSERT INTO interviews(user_id,role,score,answers) VALUES($1,$2,$3,$4)",[req.user.id,req.body.role||"",score,JSON.stringify(answers)]);res.json({score,answered:answers.length,feedback:"Use specific examples, clear structure, and measurable outcomes. For behavioral answers, try Situation → Task → Action → Result."})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
init().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("CareerNexa listening on "+PORT))).catch(e=>{console.error(e);process.exit(1)});
